### ISSUE TITLE
Role tries to agressively install Java

### ISSUE THREAD

**Issue by mikkoz** [Stouts/Stouts.logstash#4]
In relation to PR #3 , I suggest this should be handled somewhat more delicately, since it potentially conflicts with other roles that rely on there being a Java runtime available (especially Java 8). Does a simple check for an existing Java installation (with a version minimum) sound good?

**Comment by klen** [comment]
Users still have possibility to remove java from `logstash_apt_common_pkgs` option. But I think it will be enough to add option like `logstash_install_java`, mb pr?

**Comment by mikkoz** [comment]
The general problem, in my opinion, is that the Java installation functionality is tightly coupled to the main installation task, whereas it really shouldn't be. Yeah, a PR sounds good, I'll look into that :).
